# Build the Go Binary.
FROM golang:1.23 AS build_sales
ENV CGO_ENABLED=0
ARG BUILD_REF

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service/apis/services/sales
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.20
ARG BUILD_DATE
ARG BUILD_REF
RUN addgroup -g 1000 -S sales && \
    adduser -u 1000 -h /service -G sales -S sales
COPY --from=build_sales --chown=sales:sales /service/apis/services/sales/sales /service/sales
WORKDIR /service
USER sales
CMD ["./sales"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="Paul Ohrt <paul.ohrt@me.com>" \
      org.opencontainers.image.source="https://github.com/zaouldyeck/webservice/tree/main/apis/services/sales" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Paul Ohrt"